name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  destroy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Ensures manual-only
    needs: []  # No dependencies

    env:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name:  Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./Eks-terraform

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./Eks-terraform
