name: Destroy AWS Infrastructure and Docker Resources

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./Eks-terraform

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./Eks-terraform

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Remove Docker images
      run: |
        docker rmi -f medusa-backend:latest
        docker rmi -f 207268090422.dkr.ecr.us-east-1.amazonaws.com/medusa-backend:latest || true

    - name: Remove Docker containers
      run: |
        docker ps -a -q | xargs docker rm -f || true

    - name: Remove Docker volumes
      run: |
        docker volume ls -q | xargs docker volume rm || true
